DEFAULT_SETTINGS_STRING = (
    "#import my-common-styles.nomnoml\n"
    + "#arrowSize 1\n"
    + "#bendSize 0.3\n"
    + "#direction down\n"
    + "#gutter 5\n"
    + "#edgeMargin 0\n"
    + "#gravity 1\n"
    + "#edges hard\n"
    + "#background transparent\n"
    + "#fill #eee8d5; #fdf6e3\n"
    + "#fillArrows false\n"
    + "#font Calibri\n"
    + "#fontSize 12\n"
    + "#leading 1.25\n"
    + "#lineWidth 3\n"
    + "#padding 8\n"
    + "#spacing 40\n"
    + "#stroke #33322E\n"
    + "#title filename\n"
    + "#zoom 1\n"
    + "#acyclicer greedy\n"
    + "#ranker network-simplex\n"
)
